name: Go

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21' ]
    name: Go ${{ matrix.go }} sample
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM
      run: |
        syft . -o table=sbom-table.txt

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Run Grype vulnerability scan
      run: |
        grype . --output table --file grype-report.txt
    
    - name: Upload Security Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports-${{ github.sha }}
        path: |
          sbom-table.txt
          grype-report.*
        retention-days: 10
    
    - name: Generate Security Summary
      run: |
          echo "# Security Scan Summary" > security-summary.md
          echo "## SBOM Generation" >> security-summary.md
          echo "- SBOM table: sbom-table.txt" >> security-summary.md
          echo "" >> security-summary.md
          echo "## Vulnerability Scan Results" >> security-summary.md
          echo "### Summary" >> security-summary.md
          echo "- Grype report: grype-report.txt" >> security-summary.md
          echo "" >> security-summary.md
          echo "### Detailed Report" >> security-summary.md
          echo "See artifacts for full reports" >> security-summary.md

    - name: Comment PR with Security Summary
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('security-summary.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });